# Generated by Django 2.0.7 on 2020-11-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supp_id', models.CharField(max_length=20, null=True)),
                ('cust_id', models.CharField(max_length=20, null=True)),
                ('item_id', models.CharField(max_length=20, null=True)),
                ('from_date', models.DateField(null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('book_date', models.DateField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('status', models.CharField(default='0', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supp_id', models.CharField(max_length=20, null=True)),
                ('item_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('quan', models.IntegerField(null=True)),
                ('rate', models.IntegerField(null=True)),
                ('color', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(max_length=5, null=True)),
                ('pic', models.FileField(upload_to='Images/')),
                ('status', models.CharField(default='0', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200, unique=True)),
                ('pwd', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('type_of_user', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('addr', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
